export const states = [
  'West Bengal',
  'Tamil Nadu',
  'Punjab',
  'Bihar',
  'Jammu and Kashmir',
  'Arunachal Pradesh',
  'Odisha',
  'Madhya Pradesh',
  'Jharkhand',
  'Karnataka',
  'Chhattisgarh',
];

export const cities = [
  { id: 1, name: 'N24 PARGANAS', state: 'West Bengal' },
  { id: 2, name: 'S24 PARGANAS', state: 'West Bengal' },
  { id: 3, name: 'Thoothukudi', state: 'Tamil Nadu' },
  { id: 4, name: 'Sivagangai', state: 'Tamil Nadu' },
  { id: 5, name: 'Mohali', state: 'Punjab' },
  { id: 6, name: 'Aurangabad Bihar', state: 'Bihar' },
  { id: 7, name: 'Rajouri', state: 'Jammu and Kashmir' },
  { id: 8, name: 'East Siang', state: 'Arunachal Pradesh' },
  { id: 9, name: 'Kushi Nagar', state: 'Uttar Pradesh' },
  { id: 10, name: 'West Kameng', state: 'Arunachal Pradesh' },
  { id: 11, name: 'Nabarangpur', state: 'Odisha' },
  { id: 12, name: 'Tawang', state: 'Arunachal Pradesh' },
  { id: 13, name: 'Baramulla', state: 'Jammu and Kashmir' },
  { id: 14, name: 'Tarn Taran', state: 'Punjab' },
  { id: 15, name: 'Barnala', state: 'Punjab' },
  { id: 16, name: 'Khargone (West Nimar)', state: 'Madhya Pradesh' },
  { id: 17, name: 'Malkangiri', state: 'Odisha' },
  { id: 18, name: 'Garhwa', state: 'Jharkhand' },
  { id: 19, name: 'Banka', state: 'Bihar' },
  { id: 20, name: 'Shivamogga (Shimoga)', state: 'Karnataka' },
  { id: 21, name: 'Debagarh', state: 'Odisha' },
  { id: 22, name: 'Nawapara', state: 'Odisha' },
  { id: 23, name: 'Sonepur', state: 'Odisha' },
  { id: 24, name: 'Koria', state: 'Chhattisgarh' },
  { id: 25, name: 'Boudh', state: 'Odisha' },
];