export const states = [
  { id: 1, name: 'Telangana' },
  { id: 2, name: 'Andhra Pradesh' },
  { id: 3, name: 'Arunachal Pradesh' },
  { id: 4, name: 'Assam' },
  { id: 5, name: 'Bihar' },
  { id: 6, name: 'Chhattisgarh' },
  { id: 7, name: 'Delhi' },
  { id: 8, name: 'Goa' },
  { id: 9, name: 'Gujarat' },
  { id: 10, name: 'Haryana' },
  { id: 11, name: 'Himachal Pradesh' },
  { id: 12, name: 'Jammu and Kashmir' },
  { id: 13, name: 'Jharkhand' },
  { id: 14, name: 'Karnataka' },
  { id: 15, name: 'Kerala' },
  { id: 16, name: 'Lakshadweep' },
  { id: 17, name: 'Madhya Pradesh' },
  { id: 18, name: 'Maharashtra' },
  { id: 19, name: 'Manipur' },
  { id: 20, name: 'Meghalaya' },
  { id: 21, name: 'Mizoram' },
  { id: 22, name: 'Nagaland' },
  { id: 23, name: 'Odisha' },
  { id: 24, name: 'Puducherry' },
  { id: 25, name: 'Punjab' },
  { id: 26, name: 'Rajasthan' },
  { id: 27, name: 'Sikkim' },
  { id: 28, name: 'Tamil Nadu' },
  { id: 29, name: 'Tripura' },
  { id: 30, name: 'Uttarakhand' },
  { id: 31, name: 'Uttar Pradesh' },
  { id: 32, name: 'West Bengal' },
  { id: 33, name: 'Central' },
  { id: 34, name: 'Chandigarh' },
  { id: 35, name: 'Dadra and Nagar Haveli' },
  { id: 36, name: 'Daman and Diu' },
  { id: 37, name: 'Andaman and Nicobar Islands' },
];